version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: pedroloreti/dimex-backend:latest
    restart: always

    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/postgres?schema=public
    depends_on:
      - db 


  db:
    image: postgres:17
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - "80:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

    restart: always

volumes:
  postgres_data:
